### ISSUE TITLE
Source IP is dropped

### ISSUE THREAD

**Issue by aleung** [stagecoachio/udp-load-balancer#4]
I read the source code. Seems that the source IP is dropped when the packet is forwarded to server. So this load balancer works only in single direction and the server is no way to response to client. Do I understand correctly?

**Comment by felixcarmona** [comment]
yes, you are right, this is why this is named **UDP** (fire and forget) load balancer and not **TCP** load balancer.
Regards

http://serverfault.com/questions/8981/what-is-the-difference-between-udp-and-tcp

**Comment by aleung** [comment]
Some protocols base on UDP are in client/server model with bi-direction communication, e.g. RADIUS. The server replies to client with UDP packet reversing source/destination addresses and ports. 

Anyway, now I know that your load balancer works only for traffics in fire and forget mode.
